### ISSUE TITLE
Kinematic viscosity of various solutions

### ISSUE THREAD

**Issue by juanchon998** [AguaClara-Reach/aguaclara#134]
https://github.com/AguaClara/aguaclara/blob/af05d18b90c986026353f7c2fc55c9280845d4d0/aguaclara/core/constants.py#L9

Hello! 

I'm not sure if I'm looking at the latest version of this file, but the viscosity and density of water should be dependent on temperature. [Temperature can have a significant effect on viscosity from 0 to 25 °C](https://www.engineeringtoolbox.com/water-dynamic-kinematic-viscosity-d_596.html?vA=10&units=C#).

**Comment by monroews** [comment]
agreed. The design input should include a temperature. We already have functions for viscosity and density of water as a function of temperature in physchem. Thus this constant should be deleted.

**Comment by monroews** [comment]
viscosity is now defined in 3 places. It is defined as a constant, it is defined as in physchem and it is defined in CDC. 

I'd propose that kinematic viscosity should only be defined in physchem and should include both water and the various solutions (alum, PACl, chlorine)

**Comment by oliver-leung** [comment]
@monroews Do you happen to have references on how to calculate dynamic viscosity and density of these other solutions? We'll be able to make functions to find kinematic viscosity once we have those quantities.

**Comment by monroews** [comment]
The viscosity for alum and PACl is in the [CDC](https://github.com/AguaClara/aguaclara/blob/master/aguaclara/design/cdc.py) code. The viscosity of chlorine can be assumed to be the same as water for now. All of those viscosity functions should go in the same place. I'm guessing that will be in physchem.

I'm going to try to find the source data for these equations because it isn't clear if these equations are based on the concentration of aluminum or the concentration of the granular material.
[mathcad sheet](https://drive.google.com/open?id=0Bxg9Bb3XCvD1bzJhMS1Bak9PdFU) 
see [fcm extras slide 39](https://github.com/AguaClara/CEE4520/blob/master/Lectures/Extras/Flow%20Control%20and%20Measurement%20Extras.pptx)

**Comment by monroews** [comment]
I've added the equations used to fit the data for kinematic viscosity to the [AguaClara textbook](https://aguaclara.github.io/Textbook/Flow_Control_and_Measurement/FCM_Design.html#kinematic-viscosity-of-coagulants). These equations are for design of chemical dose controllers and provide the kinematic viscosity of coagulants prepared from granular alum or granular PACl.  The temperature dependency is a guess. I don't like these equations because we don't know what the aluminum concentration was for these samples. Thus the concentration in these equations is the mass of granules per volume of solution rather than the preferred mass of aluminum per volume of solution. For now this is the best we have.

**Comment by oliver-leung** [comment]
I will be working on implementing this soon! I will need to:
- Move kinematic viscosity functions under `physchem`
- Update pipeline design code to use PACl and Alum solution kinematic viscosities when specified
