### ISSUE TITLE
[BUG] Incorrect display of significant digits in ut.round_sf

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#164]
The algorithm for setting the number of digits to show after the decimal appears to be incorrect.

print(ut.round_sf(986.2536410,4)) yields 986.3. This is correct.
ut.round_sf(986.2536410,3) yields 986.0. It should give 986
print(ut.round_sf(986.2536410,2)) yields 990.0. It should give 990

**Comment by oliver-leung** [comment]
This is a side effect of Python - because you're passing in numbers of type `float`, the function retains that type. If you were to pass in an `int`, it would remain an `int`:

```python
>>> ut.round_sf(986,2)
990
```

The number should still function the same in subsequent calculations. If you want a value to be printed without the trailing ".0", a quick fix would be:

```python
>>> int(ut.round_sf(986.2536410,2))
990
```

Would you like for this type-checking to be automated within the function?

**Comment by monroews** [comment]
Thanks! I don't think we should change to integers because that could have unintended consequences. I think units require floats. So let's leave this as it is. I guess in the Python world the most important thing to show is that the object is a float and not an int. In the engineering world the most thing to show is the right number of significant digits. Those two value systems clash here!
