### ISSUE TITLE
Fix AppVeyor build

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara-Reach/aguaclara#217]
According to [this issue](https://github.com/appveyor/ci/issues/3029) that I opened on the AppVeyor  repo, the reason why AppVeyor never builds properly is because the build is somehow run under @HannahSi's account, but I believe that the secret was encrypted under @ethan92429's account.

Is there some way that we can switch the build to run under Ethan's account? Or better yet, could we encrypt a new secret under the AguaClara account and then switch the build to run under that?

**Comment by HannahSi** [comment]
That's strange, I'm not sure why it's running under my account, but I definitely agree we should have it encrypted and running either under Ethan's account or a shared AguaClara account, as we did for the new Atom sync settings last semester. 

@ethan92429 I can't find any way to view or update the account under which Appveyor is running. As the owner, are you able to change this? One odd thing I found is that I am a collaborator to your account, but the settings I can access are still very limited.

**Comment by IlyaFinkelshteyn** [comment]
We can move AppVeyor project between AppVeyor accounts for you. We need a email request to team@appveyor.com and it should CC owners of both accounts. Or @oliver-leung can simple re-encrypt the secret under `HannahSi` AppVeyor account.

P.S. Please do not confuse AppVeyor [account](https://www.appveyor.com/docs/team-setup/#account) with GitHib one. Their names are often match, but AppVeyor account is technically a separate thing.

**Comment by oliver-leung** [comment]
Something that confuses us is that, when we open new pull requests on this repository, AppVeyor builds always fail initially ([like this one](https://ci.appveyor.com/project/HannahSi/aguaclara/builds/26075947)) since they're running under Hannah's account. But if we look away for about 30 minutes, they suddenly are succeeding under Ethan's account ([like this one](https://ci.appveyor.com/project/ethan92429/aguaclara/builds/26075370)).

Something that I also noticed is that when Hannah and I log into AppVeyor, we see this project failing under our accounts, but when we switch to Ethan's account (on which Hannah and I are collaborators) using the drop-down menu in the top left, we see the passing build. I'm guessing that AppVeyor looks at all accounts that a given repository exists under until it reaches a passing build - is that correct @IlyaFinkelshteyn?

In that case, the simplest fix would just be for Hannah and I to delete the repo from our own accounts and leave it on Ethan's account.

**Comment by IlyaFinkelshteyn** [comment]
Your are correct, though let me say the same using a little bit more correct terminology.
Those are different **AppVeyor projects** connected to the same **GitHub repo**. Each project starts building on a new commit because when you create AppVeyor project, AppVeyor adds **GitHub webhook** to be notified. Each project sets **GitHub commit status** as it finished as long as parent **AppVeyor account** is authorized to do that. Indeed easiest way is to just delete unneeded **AppVeyor project** to have a proper **GitHub status** (and save a little bit of precious compute resources for AppVeyor :)). If you do not want to delete, you can simple effectively disable it with `Do not build on "Push" events` and `Do not build on "Pull request" events` check boxes on General Settings page.

**Comment by oliver-leung** [comment]
Hannah and I have deleted the AppVeyor projects under our AppVeyor accounts for this GH repo, and our PR's are building correctly. Thank you very much @IlyaFinkelshteyn for your help!

**Comment by HannahSi** [comment]
That's great news, I appreciate your help as well @IlyaFinkelshteyn !
