### ISSUE TITLE
1.5 inch pipe missing from pipe database

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#235]
Please add 1.5" pipes to the pipe database (in the core functions). We need 1.5" pipe for the backwash branches in the filter.

**Comment by monroews** [comment]
@HannahSi could you make this small change so that I can get the array of nominal diameters and the arrays of ID and OD for all of the pipes including 1.5". TUrns out that 1.5 inch is needed for our filter design and I'm working on that currently.

**Comment by HannahSi** [comment]
The 1.5" pipe has been added in release 0.1.11! 

About our conversation on applying the list handler to `core.pipes`... It turns out that the version of the list handler I have been working with is **not able to handle outputs with units other than `u.dimensionless`**, so I was not able to apply the list handler to the functions in pipes. I'll add fixing this bug to #205.
