### ISSUE TITLE
link to old version of pint

### ISSUE THREAD

**Issue by monroews** [AguaClara-Reach/aguaclara#271]
The install requirements currently link to an old version of pint. Is there a reason not to use the current version of Pint and thus speed up the install on Colab? In Colab it has to uninstall Pint 0.12 to revert to the old version of Pint.

Found existing installation: Pint 0.12
    Uninstalling Pint-0.12:
      Successfully uninstalled Pint-0.12
Successfully installed aguaclara-0.2.1 pint-0.8.1

**Comment by HannahSi** [comment]
The required Pint version was set to 0.8.1 to solve issue #155. When I briefly tried testing the package with version 0.12, I didn't find the same errors as before, but a few other tests did fail. We'll look into what it takes to make this upgrade.

**Comment by HannahSi** [comment]
The failing tests turned to be caused by round off errors. I believe I've fixed all of them on branch `hs649/upgrade-pint`.

Note to self: remember to update pint versions in Pipfile.lock.

**Comment by HannahSi** [comment]
The Pint version has been upgraded to the latest version (0.16.1) on my branch. A few precision-related errors remain in the doctests of the `aguaclara.design` modules. For example, this doctest at the beginning of `sed_tank.py`:

```python
""" ...
Example:
    >>> from aguaclara.design.sed_tank import *
    >>> sed_tank = SedimentationTank(q = 60 * u.L / u.s)
    >>> sed_tank.diffuser_hl
    <Quantity(0.009259259259259259, 'centimeter')>
"""
```
results in the following error ([see outputs in Travis build](https://travis-ci.org/github/AguaClara/aguaclara/builds/743511541#L490-L499)) while running `make doctest`:
```
Failed example:
    sed_tank.diffuser_hl
Expected:
    <Quantity(0.009259259259259259, 'centimeter')>
Got:
    <Quantity(0.00925925926, 'centimeter')>
``` 
@oliver-leung and @ryan26192, what are your thoughts on modifying the example code to prevent round-off errors, e.g. `round(sed_tank.diffuser_hl, 6)`? Alternatively, since precision might vary again with future versions of Pint and between computers in general, and the `aguaclara.design` modules are already pytest-ed in test files, would it be worth turning these doctests into static RST code blocks?

**Comment by ryan26192** [comment]
I think modifying the code to prevent round off errrors with the round function makes a lot of sense, if we keep a normal amount of sig figs (3,4, or 5) it would probably be free from errors surrounding pint

**Comment by HannahSi** [comment]
Sounds good, thanks for your input! I'll use the round function in the doctests.
