### ISSUE TITLE
ID to OD function and standardized names in pipes.py

### ISSUE THREAD

**Issue by HannahSi** [AguaClara-Reach/aguaclara#279]
Several updates can be made to `core/pipes.py`:

1. **A class and/or static method should be defined to convert ID and SDR to the minimum available OD.** A class could ask for SDR and minimum ID in the constructor and include methods for available ID, ND, and OD.  A static method could calculate OD from ID and SDR and use the existing `od_available(od_guess)` method, or calculate ND using `ND_SDR_available(ID, SDR)` and convert ND to OD.

2. **Method and method parameter names should be standardized.** For example, `ND_available(NDguess)` and `od_available(od_guess)` have different formats.

3. **All methods and classes should be fully and properly documented.** "Properly documented" means the descriptions should be accurate and include only information helpful to users (implementation instructions and internal variable names like `pipedb` would not be helpful).

4. **Functions ending in `all_available` can be made more efficient.** For example, most of the computation in `ND_all_available()` can be implemented one-line conditional indexing: `return pipedb['NDinch'][pipedb['Used'] == 1]`.

**Comment by annabel48lin** [comment]
@monroews   I'm wondering how users would normally use pipes.py. Right now, we are considering making a Pipe class whose constructor has optional fields so that users can perform calculations quicker. 2 possibilities: 

SDR is required
- similar to current implementation
- will users ever want to calculate SDR from other variables?
- will users be annoyed if they can't make a schedule 40 pipe if they don't know SDR?
     - then, they will need to use static methods to get ID. Will they want to get the other properties of the pipe easily? (so they don't have to keep calling static methods)

boolean for whether the pipe is a schedule 40 pipe. 
- SDR will not be required if the pipe is schedule 40 
- users can then access other properties of the pipe like ID and OD after creating the pipe
- will users ever want to change whether or not a pipe is schedule 40?

We want to make pipes.py as convenient as possible for users, but we are not exactly sure what users would prefer and what they know/don't know/want to know about each pipe.

**Comment by monroews** [comment]
the common use case is use hydraulic equations to calculate a minimum ID
use structural constraints, product availability, or max pressure to set the SDR
given minID and SDR, find the corresponding ND and the actual ID.
Take the actual ID to find actual hydraulic performance.

I don't see a need for a user to calculate and SDR EXCEPT you could add the case for converting a max pressure into an SDR.
It would be cool if you could make the calculations work for schedule 40, 80 120 and160 pipes too.  In that case the user might calculate the minID and an SDR required for their purposes and then the python code would find the pipe ND and schedule (40, 80, 120, 160).
In this solution scheme SDR would still be required. An alternative would be to require the max pressure and use the max pressure to find the right schedule.

I wasn't sure on your last question. It should be possible to select either SDR pipes or schedule pipes. Perhaps that would be a enum that would default to SDR.

I'm delighted that you are working to improve these functions!

**Comment by annabel48lin** [comment]
@monroews Thank you! Can you clarify on "the python code would find the pipe ND and schedule (40, 80, 120, 160)" and how you would find the schedule for a pipe (from minID & SDR or from pressure)? Also, does this refer to existing methods like [physchem.pipe_ID](https://github.com/AguaClara/aguaclara/blob/a28dd036115f98e3a2b0b74c1b3d41b4c46ca72a/aguaclara/core/physchem.py#L1535-L1550) and [Pipe.id_sch40](https://github.com/AguaClara/aguaclara/blob/a28dd036115f98e3a2b0b74c1b3d41b4c46ca72a/aguaclara/core/pipes.py#L36-L39) or is it a functionality that is wanted but not yet implemented?

**Comment by monroews** [comment]
I believe this would be new functionality because SDR is not constant for schedule 40 etc pipe. So given minimum ID and SDR you would search through the arrays of schedule 40 etc to find the pipe that meets that criteria. Note that you would need to calculate the SDR for each pipe in the arrays of schedule 40 etc. SDR is OD/wall thickness.

**Comment by annabel48lin** [comment]
Work plan:
	- find PVC schedule chart and update database
	- work on SDR pipes 
		○ include ID_sched_ for all schedules (use enums?)
		○ let users specify what set of schedules or NDs they want to use
	- create schedule pipes
		○ client specifies maxSDR, minID. Find schedule and ND that satisfies this. 
	- convert between SDR and schedule using SDR and ID
